[project]
name = "birdnet-predictions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "birdnetlib>=0.18.0",
    "librosa>=0.11.0",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "tensorflow==2.15.1",
    "tqdm>=4.67.1",
]
